package exception;

public class exceptiondemo {

	public static void main(String[] args) {
		int x=10;
		int y=0;
		int z=x/y;
		System.out.println(z);
		/*
		 * we use try catch method
		 * {
		 * int x=10;
		 * int y=0;
		 * try
		 * {
		 * int z=x/y;
		 * }
		 * catch(Exception e)
		 * {
		 * system.out.print(e);
		 * }
		 * 
		 */
		
	}

}
